# Generated by Django 4.2.23 on 2025-07-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(default='D000', max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('password', models.CharField(default='default123', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hauler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hauler_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HaulerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.driver')),
                ('hauler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.hauler')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='hauler_code',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tracking.hauler'),
        ),
    ]
