# Generated by Django 4.2.23 on 2025-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hauleractivity',
            name='shift',
            field=models.TextField(default='DAY', max_length=50),
        ),
    ]
